### ISSUE TITLE
[Feature Request] Mockingboard

### ISSUE THREAD

**Issue by AnalogRain** [audetto/AppleWin#3]
Would it be feasible to add the mockingboard as an option for sound in Qapple? I know the original AppleWin has it so you might be able to it for reference.

**Comment by audetto** [comment]
This is complicated.

In particular because I have no experience with it. My Apple ][ e did not have it so I have never used it.

What one could do, would be to 1) enable the card in the emulator only (no real world output) and later 2) play some real sound.

Do you have a simple example of some code using it? A game, a BASIC program...
What is your level of C++ programming?

Ideally AppleWin should try to clearly separate Emulator World (Windows / Linux) from Emulated World (Apple ][), which are now very interconnected.

**Comment by AnalogRain** [comment]
I don't have a simple example of a program using a mockingboard unfortunately, i know Ultima 3 used it, but thats far from simple. I have experience with C but not C++ and no experience with Qt. So yeah, I understand that it may be too hard to impliment, ill ask a friend if he knows of any simple mockingboard programs.

**Comment by AnalogRain** [comment]
I found this mini-manual for the mockingboard, im going to look for more resources http://apple2.org.za/gswv/a2zine/Docs/Mockingboard_MiniManual.html

**Comment by AnalogRain** [comment]
Here is a pdf of the actual manual for the mockingboard https://mirrors.apple2.org.za/ftp.apple.asimov.net/documentation/hardware/sound/Mockingboard%20D%20Manual.pdf

**Comment by audetto** [comment]
I've made good progress on integrating the Mockingboard.
I only need to play the sound now.

https://github.com/audetto/AppleWin/tree/mockingboard

**Comment by audetto** [comment]
It nows plays audio.
I need to do some better tests, but it is mostly done.

**Comment by audetto** [comment]
Standard Mockingboard works.
But see https://github.com/audetto/AppleWin/issues/8
