### ISSUE TITLE
Debugger console doesn't handle mouse text

### ISSUE THREAD

**Issue by sh95014** [audetto/AppleWin#93]
sa2 running in macOS:
<img width="595" alt="Screenshot 2023-06-01 at 10 18 42 AM" src="https://github.com/audetto/AppleWin/assets/95387068/f40280ca-ca2a-4f39-8bad-0ecf642d856d">

AppleWin:
<img width="726" alt="Screenshot 2023-05-31 at 7 07 35 PM" src="https://github.com/audetto/AppleWin/assets/95387068/99f78fff-1dc5-464b-84a0-e068c3ae74b9">

**Comment by audetto** [comment]
I know.

I would like to make some improvements to the fond

- maybe use this font for the debugger: https://github.com/AppleWin/AppleWin/issues/538#issuecomment-1086133719
- allow to change the font size

**Comment by sh95014** [comment]
For macOS I actually just gave up and loosely mapped the mouse text to Unicode:

"⬉⌛︎✓☑︎↵�←…↓↑‾↵█⇤⇥⤓⤒―⌞→▦▩⟦⟧⎥♦︎�✛⊡⎢"

(The first two are the "closed apple" and "open apple" glyphs, both of which I mapped to the Apple logo private-use glyph.)

**Comment by audetto** [comment]
This is the font I was given

https://fontstruct.com/fontstructions/show/1912741/debug6502

I will try to re-integrate it.

**Comment by Michaelangel007** [comment]
There were a couple of reasons a custom font was used:

* Proper and accurate MouseText due to incomplete Unicode support at the time. (Not sure if this is still an issue?)
* Custom numbers with a box around them used for the Debugger's bookmarks.  (Unicode U+24EA, U+2460, U+2468, ..., U+2468

This usenet post has some details on Unicode mapping for anyone curious:
https://groups.google.com/g/comp.sys.apple2/c/8VTjK-kMZXo/m/oVwjRFNHAwAJ

**Comment by audetto** [comment]
Debugger now uses https://fontstruct.com/fontstructions/show/1912741/debug6502

@Michaelangel007 your font works well but there is a missing character in the area 0xDD - 0xDF (which btw is not used by AW)
